/*
 * TODO: Review argument and return types:

Import[11]:
 - func[0] sig=2 <__wasi_args_sizes_get> <- wasi_snapshot_preview1.args_sizes_get
 - func[1] sig=2 <__wasi_args_get> <- wasi_snapshot_preview1.args_get
 - func[2] sig=3 <__wasi_proc_exit> <- wasi_snapshot_preview1.proc_exit
 - func[3] sig=20 <__wasi_clock_time_get> <- wasi_snapshot_preview1.clock_time_get
 - func[4] sig=2 <__wasi_clock_res_get> <- wasi_snapshot_preview1.clock_res_get
 - func[5] sig=2 <__wasi_environ_sizes_get> <- wasi_snapshot_preview1.environ_sizes_get
 - func[6] sig=2 <__wasi_environ_get> <- wasi_snapshot_preview1.environ_get
 - func[7] sig=4 <__wasi_fd_close> <- wasi_snapshot_preview1.fd_close
 - func[8] sig=8 <__wasi_fd_read> <- wasi_snapshot_preview1.fd_read
 - func[9] sig=8 <__wasi_fd_write> <- wasi_snapshot_preview1.fd_write
 - func[10] sig=21 <__wasi_fd_seek> <- wasi_snapshot_preview1.fd_seek
Type
 - type[2] (i32, i32) -> i32
 - type[3] (i32) -> nil
 - type[4] (i32) -> i32
 - type[8] (i32, i32, i32, i32) -> i32
 - type[20] (i32, i64, i32) -> i32
 - type[21] (i32, i64, i32, i32) -> i32
*/

#include <stdint.h>

#define MAGIC_ERROR_NUMBER 0xdbcd

// NOTE: Return vals should be __wasi_errno_t (uint16_t)

// Always succeeds, sets argc and arg_str_size to zero.
// Arg types: __wasi_size_t <- What is this?
int args_sizes_get(int *argc, int *arg_str_size) {
    *argc = 0;
    *arg_str_size = 0;
    return 0;
}

// Always succeeds. Due to `args_sizes_get` always returning a zero arg count,
// this function should never be called by the generated C code. Leaves the
// arguments untouched.
int args_get(uint8_t **_argv, uint8_t *_argv_buf) {
    return 0;
}

// No-op.
// Arg type: __wasi_exitcode_t
void proc_exit(uint32_t _exit_code) {}

extern uint64_t clock_getTimestamp();
// Arg types: __wasi_clockid_t, __wasi_timestamp_t, __wasi_timestamp_t*
int clock_time_get(uint32_t clockid, uint64_t precision, uint64_t *ret) {
    // MONOTONIC only.
    if (clockid != 1) return MAGIC_ERROR_NUMBER; // FIXME: Better error val.

    *ret = clock_getTimestamp() * 1000000000; // 1 second == 1e9 nano-seconds
    return 0;
}

// Only supports clockid == 1.
int clock_res_get(uint32_t clockid, uint64_t *ret) {
    if (clockid != 1) return 28; // errno::inval -> __WASI_ERRNO_INVAL -> 28
    *ret = 1000000000; // 1 second == 1e9 nano-seconds.
    return 0;
}

// Always succeeds, sets envc and env_str_size to zero.
// Arg types: __wasi_size_t
int environ_sizes_get(int *envc, int *env_str_size) {
    *envc = 0;
    *env_str_size = 0;
    return 0;
}

// Always succeeds. Due to `environ_sizes_get` always returning a zero env count,
// this function should never be called by the generated C code. Leaves the
// arguments untouched.
int environ_get(uint8_t **a, uint8_t *b) {
    return 0;
}

// Always succeeds. An alternative is provided by DreamBox and the family of
// fd_* functions referenced in the Wasm generated by Koka are never actually
// used. Therefore, the argument is left untouched.
int fd_close(int a) {
    return 0;
}

// Always fails. Shouldn't ever be used as DreamBox provides alternatives.
// Arguments are left untouched.
int fd_read(int a, int b, int c, int d) {
    return -1;
}

// Always fails. Shouldn't ever be used as DreamBox provides alternatives.
// Arguments are left untouched.
int fd_write(int a, int b, int c, int d) {
    return -1;
}

// Always fails. Shouldn't ever be used as DreamBox provides alternatives.
// Arguments are left untouched.
int fd_seek(int a, int64_t b, int c, int d) {
    return -1;
}
